### ISSUE TITLE
Installing ROS

### ISSUE THREAD

**Issue by jasilberman** [f1tenth/f1tenth_doc#19]
I have missed on the instruction the initial ROS install

> You might need to install some additional ROS packages.
> 
> For ROS Kinetic:
> 
> $​ sudo apt-get update
> $​ sudo apt-get install ros-kinetic-driver-base

I hope this helps.
Thanks 
Jack

Assuming ROS was not installed yet:

sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
sudo apt-get update
sudo apt-get install ros-melodic-driver-base

**Comment by kimnluong** [comment]
Instructions for installing ROS can be found here: https://f1tenth.readthedocs.io/en/latest/getting_started/software_setup/software_host.html

**Comment by jasilberman** [comment]
Hi Kim,
What I meant is if one gets to that point without installing ROS, the instruction will fail. And if they already installed ROS at the Jetson, then they would not need those lines to install ROS... 
IMO, either we should assume that people have installed ROS at the Jetson, then no need to install it again,  or add the link to where they should  install ROS at the Jetson before proceeding. I hope I am making sense. Thanks for all the work. Jack

**Comment by hzheng40** [comment]
Hi Jack,
The instructions are in order where you have to install ROS before you get to this step.
Also, this line is not installing ROS. driver_base is a ROS package.
