### ISSUE TITLE
Latest VESC Tool - No VESC_servoout.bin

### ISSUE THREAD

**Issue by jasilberman** [f1tenth/f1tenth_doc#30]
**Describe the bug**
I just downloaded the latest VESC Tool - 2.05
I can't find the option for the VESC_servoout.bin anymore.
Yes, I have the Show non-default firmwares selected. Done this few times before. 
They may have stopped supporting VESC_servoout.bin on latest firmware (5.1) or they have not released the VESC_servoout.bin yet for 5.1 yet.

**To Reproduce**
Install the latest VESC Tools, connect to the VESC, select Show non-default firmwares, try to find VESC_servoout.bin.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kimnluong** [comment]
Edited firmware section and uploaded older version of .bin file to drive.

**Comment by jasilberman** [comment]
Kim, 

Do you want the firmware version 4.2 that has VESC_servoout.bin that will work with VESC HW versions 4.12?

Alternatively, you can suggest people to use VESC Tools 2.03.
I can write the instructions to use VESC HW version 4.12. These are < US$60 on-line.
Just let me know.
Thank you,
-Jack

**Comment by kimnluong** [comment]
Hi Jack,

That would be great! Could you submit the write up as pull request instead? I'll add it to the documentation. thanks!
