### ISSUE TITLE
VESC HW 4.12

### ISSUE THREAD

**Issue by jasilberman** [f1tenth/f1tenth_doc#31]
**Describe the bug**
Addition to the VESC HW V4.12 instructions

"
VESC out of sync errors: Check that the VESC is connected. If the error persists, make sure you’re using the right VESC driver node. Currently, the vesc package in the f110_system repo only supports VESC 6+. If you have an older implementation of VESC (for example the FOCBox), use the repo here instead.
"
One needs to indicate the firmware needed to be compatible with the MIT vesc_driver. The driver expects firmware 2.18. But it will not work with the VESC Tools you have on the F1/10 instructions.

See proposed solution below.

**To Reproduce**
VESC HW4.12.
At this point I am using VESC Tool V2.03. It supplies the latest firmware that I could find that has VESC_servoout.bin. As of 28Apr20, the latest VESC Tool is 2.05.  It has firmware 5.1. I don’t see vesc_servoout.bin available with it...

I uploaded firmware V4.2 VESC_servoout.bin to the VESC HW 4.12
The BLDC sensored motor was detected without problems.

Need to use this repository to build the vesc_driver into the ROS
This is how you can do it. Adjust your paths accordingly
ssh to the jetson

cd ~/projects/f110/f110_ws/src/f110_system
rm -rf vesc
git clone https://github.com/erwincoumans/vesc
cd ~/projects/f110/f110_ws
catkin_make
source devel/setup.bash

No errors during the catkin_make ...
That is all.

A quick test with your robot framework with the joystick should do it
ex using F1/10. On a terminal tab

source devel/setup.bash
roscore

Another terminal tab
roslaunch racecar teleop.launch

I had to adjust the axis of my joystick
~/projects/f110/f110_ws/src/f110_system/racecar/racecar/config/racecar-v2/joy_teleop.yaml

I changed the axis to map the jstest I ran
     
axis: 4        target: drive.speed                    
axis: 0        target: drive.steering_angle

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hzheng40** [comment]
Hi Jack,
Is the issue is regarding older VESC hardware?
It might help us understand the proposed changes more to create a Pull Request.

**Comment by kimnluong** [comment]
Resolved. (see previous issue request)

**Comment by jacksilb** [comment]
Hi Kim,

Yes. This is to enable HW V4.12. The price of these are <US$60 shipped to the US. Much more affordable for the initial  build and replacements.
 
I believe I got it working. It needs firmware V4.2 (lastest version I found  with VESC_servoout.bin).

Thank you,
-Jack

**Comment by jacksilb** [comment]
Sorry. Just saw your other reply. This became duplicate.
Thank you
-Jack
