### ISSUE TITLE
A problem in documentation 

### ISSUE THREAD

**Issue by sadransh** [f1tenth/f1tenth_doc#35]
Something is confusing in this step : 

https://f1tenth.readthedocs.io/en/latest/getting_started/firmware/firmware_vesc.html#doc-firmware-vesc

the point is we have VESC HARDWARE both v4 and v6 and v6 mkIII and ... 
in the text it is mentioned the firmware is for vesc v 4.12 hardware but the photo is showing vesc v6 MkIII !

**Comment by kimnluong** [comment]
Thanks for submitting the issue request. I've updated the firmware section. You'll need to download v2.03 of the vesc tool instead of v2.05. v2.03 should contain the required servoout.bin file.

**Comment by sadransh** [comment]
@kimnluong 
Yeah the newer version (2.06) does not have servoout. 
here is a link to 2.03 ( Linux version ) 
https://drive.google.com/file/d/1tGrboseLUIlSdDjkhxDVxyopWc0h4_LC/view?usp=sharing

**Comment by kimnluong** [comment]
I have added the linux link to the documentation. Thank you so much!! Please continue to submit issue and pull requests as you find errors.
