### ISSUE TITLE
Logitech Controller Not Working

### ISSUE THREAD

**Issue by alxtee** [f1tenth/f1tenth_doc#43]
Hello,

I'm using the Logitech GamePad F710 in Direct Input Mode as per the docs, however it doesn't seem to be working properly. I'm also receiving the force feedback error which means the controller is connected. When I run `sudo jstest /dev/input/js0` it shows the controller is connected but isn't registering any controller inputs/feedback. I've looked online and it looks like the solution may involve something with a configuration file or extra compiling. 

Here is the post I found online, but I'm still not sure how to fix the issue: https://forums.developer.nvidia.com/t/no-data-being-updated-from-joystick-in-o-p-of-sudo-jstest-dev-input-js0-solved/65985

Thank you!

**Comment by travelbureau** [comment]
Can you tell us:
1. What compute platform you are using e.g. Xavier, TX2, etc.
2. What Jetpack version you are running
3. If other USB devices are working properly (especially LIDAR)
4. What carrier board your compute device is mounted to (e.g. Orbitty or you have some non-standard config).

**Comment by travelbureau** [comment]
I prefer to debug the controller using the `joy-node` package and rostopic echo rather than jstest usually...

**Comment by travelbureau** [comment]
The other potential issue is if you followed our instructions you may have set up some udev rules which remap the device are you sure that the joystick is actually connected to `/dev/input/js0`

**Comment by alxtee** [comment]
Hi thanks for the help.

1. TX2
2. 4.3
3. Everything else works fine on usb- zed, imu, mouse, etc. lidar is over
Ethernet.
4. No carrier board is being used, I’m using the MIT racecar hardware spec,
this should have no impact on the controller issue though.

Regarding the udev rules I followed everything as per the build guide and
double checked it. When using jtest port 0 is the only one which returns
anything, but the data doesn’t update.

**Comment by travelbureau** [comment]
Can you confirm that echoing the output of  joy-node shows nothing?

**Comment by travelbureau** [comment]
Also this seems silly but try flipping the slider switch on the back of the controller, and hitting the mode button and see if any of these things make a difference.

**Comment by travelbureau** [comment]
https://github.com/ros-drivers/joystick_drivers/tree/master/joy
also available by `sudo apt install ros-yourdistro-joy`

**Comment by alxtee** [comment]
Thanks for the help! It works now! Looks like it was probably a combo of installing the drivers and flipping that switch (definitely didn't suspect that was the issue). The controls work but not too well right now, calibrating the odometry will probably fix this. Will let you know if I have any more issues.
