### ISSUE TITLE
Cannot use LIDAR over ethernet and Wifi at the same time 

### ISSUE THREAD

**Issue by alxtee** [f1tenth/f1tenth_doc#45]
Currently trying to use a Hokuyo Lidar (10-lx) connect over ethernet to the Jetson Tx2 and Wifi for ssh & internet simultaneously. However, I'm only able to get one working at a time. The ideal setup is to have both my dev laptop and racecar connected to 1 router which has a passthrough into the internet, so I can have web access on both.

Here is more info on this issue: https://forums.developer.nvidia.com/t/how-to-set-wlan0-and-eth0-to-work-simutaneously-for-hokuyo-lidar/43434

The linked thread is long but one of the listed solutions is someone using a Picostation route of getting a AP hotspot, and they listed the settings they used.

I've been messing with this for a long time, I also tried the f1 tenth instruction for setting up the hotspot but it didn't work, I couldn't get my laptop to connect when the lidar was plugged in.

Thanks!

**Comment by travelbureau** [comment]
1.  An easy solution is just to get a regular usb wifi stick... not sure the access point hotspot is necessary. Try contacting Madhur Behl on the slack for more details on configuring the Picostation, he still uses them for class. 

2. I have found that some laptop wifi cards will not connect to the Jetson hotspot. I have this problem on my Ubuntu 18.04 laptop (Razer Blade 15) and we have encountered it in class. My solution is to setup a wifi router which both my machine and the car are connected to. I bring the router to events where I run the car so all the login info and network config stay the same.

**Comment by travelbureau** [comment]
I think in the future it would be good for the spec hardware to move away from the ethernet lidar. It causes a lot of issues... I will look through my notes to see if I can find any more info on a solution. I recall having helped another lab at Penn solve it last year.

**Comment by alxtee** [comment]
Ok I will see what I can do, please let me know if you find anything else.
Thank you for the help.

**Comment by alxtee** [comment]
Do you think using a ethernet to usb adapter could fix this issue? Or would the Jetson still recognize it as a network?

**Comment by travelbureau** [comment]
Unfortunately no. Someone has tried that before.
