### ISSUE TITLE
Approximate Time Investment: 5-7 hours?

### ISSUE THREAD

**Issue by jasilberman** [f1tenth/f1tenth_doc#6]
re: Approximate Time Investment: 5-7 hours at the introduction page.

I would imagine it will take more than 7 hours for someone to build the car, configure the software on the host and target, and start to drive the robot.
How about we have some new fresh people try the process from start to end and then get the typical build time listed.

Thank you,
-Jack (UC San Diego)

**Comment by kimnluong** [comment]
The build part of the car is actually pretty easy and straightforward. This I've done myself and it is doable from start to finish in an hour for an experienced hobbyist. I would say 1.5 hr is the average but I'll increase it to 2 hours just in case. The software is probably where it takes the most time. If someone already has linux and ros installed then that saves them 1-2 hours. Ah it looks like I missed a few time estimates in some of the sections and didn't add them to my guesstimate. I'll update them today. Thanks!
