### ISSUE TITLE
The discourse group link is broken - https://f1tenth.discourse.group/

### ISSUE THREAD

**Issue by yogeshbabar420** [f1tenth/f1tenth_doc#67]
**Describe the bug**
The discourse group link provided on the build documentation (https://f1tenth.readthedocs.io/en/foxy_test/) is broken - https://f1tenth.discourse.group/

**To Reproduce**
1. Go to 'https://f1tenth.readthedocs.io/en/foxy_test/'
2. Click on 'https://f1tenth.discourse.group/'
3. page no found error

**Expected behavior**
The discourse link should work

**Comment by wenchaoliu-93** [comment]
I believe the discussion has been moved to [Slack](https://join.slack.com/t/f1tenth-teams/shared_invite/zt-2e9c1cyzk-1EndpRPFnJJRBBiCPoBAQA), but it'd be great if an achieve of the Discourse were made available.
