### ISSUE TITLE
Building the Car - Bill of Materials:

### ISSUE THREAD

**Issue by jasilberman** [f1tenth/f1tenth_doc#7]
How about adding links to the parts where one can order these?
Amazon, hobby stores, McMaster-Carr...

Thanks,
-Jack

**Comment by JetsonHacksNano** [comment]
There are links, you need to scroll to the side.

**Comment by jasilberman** [comment]
LIPO (LITHIUM POLYMER) BATTERY SAFETY WARNING

We always require students to use the LiPo alarms. Would that be a good requirement?

**Comment by jasilberman** [comment]
The links are there ...
