### ISSUE TITLE
Master BOM not available

### ISSUE THREAD

**Issue by szilu7** [f1tenth/f1tenth_doc#70]
**Describe the bug**
The Master BOM Google Spreadsheet is not available in bom.rst.
https://docs.google.com/spreadsheets/d/1ykUyrZq-vLlMTf0TIcdMrRbGKcRWglW6ol76QyGst2I/edit#gid=2038095912
Access denied.

**To Reproduce**
1. Go to f1tenth_doc/getting_started/build_car/bom.rst
2. Click on Master BOM link

**Expected behavior**
It should show a Google Spreadsheet.
But it says that the organization that owns this item does not allow you to access it.

**Comment by hzheng40** [comment]
Please refer to the latest webpage build for the link: [https://f1tenth.readthedocs.io/en/foxy_test/getting_started/build_car/bom.html](https://f1tenth.readthedocs.io/en/foxy_test/getting_started/build_car/bom.html)
