### ISSUE TITLE
Problem in setting up driver stack

### ISSUE THREAD

**Issue by ruks001** [f1tenth/f1tenth_doc#73]
I am using jetson orion nano development kit. I followed all the process as mentioned in the build section. I encountered a problem during "setting up the driver stack". As mentioned in the build process, I followed following commands:
cd $HOME/f1tenth_ws
rosdep update
rosdep install --from-paths src -i -y

But in the third line: "rosdep install --from-paths src -i -y" I got following error:
WARNING: ROS_PYTHON_VERSION is unset. Defaulting to 3
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies (ROS distro is not set. Make sure `ROS_DISTRO` environment variable is set, or use `--rosdistro` option to specify the distro, e.g. `--rosdistro indigo`):
vesc_driver: Cannot locate rosdep definition for [sensor_msgs]
teleop_tools: Cannot locate rosdep definition for [ament_cmake]
mouse_teleop: Cannot locate rosdep definition for [rclpy]
teleop_tools_msgs: Cannot locate rosdep definition for [action_msgs]
vesc_ackermann: Cannot locate rosdep definition for [tf2_ros]
vesc_msgs: Cannot locate rosdep definition for [geometry_msgs]
joy_teleop: Cannot locate rosdep definition for [rosidl_runtime_py]
ackermann_mux: Cannot locate rosdep definition for [diagnostic_updater]
key_teleop: Cannot locate rosdep definition for [rclpy]
f1tenth_stack: Cannot locate rosdep definition for [std_msgs]
vesc: Cannot locate rosdep definition for [ament_cmake_auto]

Can someone please help me?

**Comment by hzheng40** [comment]
run `rosdep update --rosdestro=foxy` instead.

**Comment by ruks001** [comment]
The error is still there. output when I run "rosdep update --rosdistro=foxy" is as below:

reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip distro "ardent" different from requested "foxy"
Skip distro "bouncy" different from requested "foxy"
Skip distro "crystal" different from requested "foxy"
Skip distro "dashing" different from requested "foxy"
Skip distro "eloquent" different from requested "foxy"
Add distro "foxy"
Skip distro "galactic" different from requested "foxy"
Skip distro "groovy" different from requested "foxy"
Skip distro "humble" different from requested "foxy"
Skip distro "hydro" different from requested "foxy"
Skip distro "indigo" different from requested "foxy"
Skip distro "iron" different from requested "foxy"
Skip distro "jade" different from requested "foxy"
Skip distro "kinetic" different from requested "foxy"
Skip distro "lunar" different from requested "foxy"
Skip distro "melodic" different from requested "foxy"
Skip distro "noetic" different from requested "foxy"
Skip distro "rolling" different from requested "foxy"
updated cache in /home/ruks/.ros/rosdep/sources.cache


and when I run  "rosdep install --from-paths src -i -y" again I got following output:
WARNING: ROS_PYTHON_VERSION is unset. Defaulting to 3
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies (ROS distro is not set. Make sure `ROS_DISTRO` environment variable is set, or use `--rosdistro` option to specify the distro, e.g. `--rosdistro indigo`):
joy_teleop: Cannot locate rosdep definition for [launch_testing]
f1tenth_stack: Cannot locate rosdep definition for [std_msgs]
teleop_tools: Cannot locate rosdep definition for [ament_cmake]
key_teleop: Cannot locate rosdep definition for [ament_pep257]
vesc: Cannot locate rosdep definition for [ament_cmake_auto]
vesc_msgs: Cannot locate rosdep definition for [geometry_msgs]
teleop_tools_msgs: Cannot locate rosdep definition for [action_msgs]
vesc_ackermann: Cannot locate rosdep definition for [tf2_ros]
mouse_teleop: Cannot locate rosdep definition for [ament_xmllint]
vesc_driver: Cannot locate rosdep definition for [sensor_msgs]
ackermann_mux: Cannot locate rosdep definition for [diagnostic_updater]

**Comment by ruks001** [comment]
Thank you very much for the help. I added the same argument on the second command. 
"rosdep install --from-paths src --rosdistro=foxy -i -y"
and it works.

**Comment by hzheng40** [comment]
Did you install and init rosdep following the instructions [here](https://f1tenth.readthedocs.io/en/foxy_test/getting_started/firmware/drive_workspace.html#installing-ros-2-and-its-utilities)?
