### ISSUE TITLE
Problem while driving two cars at the same time

### ISSUE THREAD

**Issue by ruks001** [f1tenth/f1tenth_doc#74]
I have two f1tenth cars. On both of them, I followed the same steps as described in the f1tenth website. Whenever I try to drive a car manually, both of them get commands from the same joystick. I have connected both cars to different joysticks but still, both act at the same time when only one joystick is used. Do I need to change anything? Both of them are connected to the same local wifi and use "no machine". When I turn off the wifi, then only they both ack separately.

**Comment by hzheng40** [comment]
Make sure you're setting different ROS_DOMAIN_ID environment variables on the two cars, or they'll be sharing all topics.
See [here](https://docs.ros.org/en/foxy/Concepts/About-Domain-ID.html) for more details.
