### ISSUE TITLE
Flashing the TX2 with the Orbitty Carrier

### ISSUE THREAD

**Issue by jasilberman** [f1tenth/f1tenth_doc#8]
Suggestion 

Between [1] and [2]

# check if the TX2 shows in the USB devices. Otherwise, don't go to [2] because it wont work
lsusb

> Bus 001 Device 020: ID 0955:7020 NVidia Corp.

2. On the Pit/Host computer manually flash the boards by typing the following into the terminal

**Comment by kimnluong** [comment]
Updated. thanks!
