### ISSUE TITLE
LIPO (LITHIUM POLYMER) BATTERY SAFETY WARNING

### ISSUE THREAD

**Issue by jasilberman** [f1tenth/f1tenth_doc#9]
We always require students to use the LiPo alarms. Would that be a good requirement?

**Comment by kimnluong** [comment]
Right now, the balancer port of the battery is used to power the powerboard. The current powerboard (V4) on the vehicle does not have space to put a Lipo alarm. V8 powerboard (same size as V4) will have a port for the lipo alarm.
